#user-service yml

# Service registers under this name
spring:
  application:
    name: ToDo-Microservice-UserService

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

# HTTP Server (Tomcat) Port
server:
  port: 9700

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false